### ISSUE TITLE
Fix chunkator when the primary key is a OneToOneField

### ISSUE THREAD

**Issue by zebuline** [novafloss/django-chunkator#19]
django-chunkator orders by `pk`.

But sometimes, you want to order by an explicit field.

For example:

```python
class ModelA(models.Model):
    name = models.CharField(max_length=20)

    class Meta:
        ordering = ['name']


class ModelB(models.Model):
    modela = models.OneToOneField(ModelA, primary_key=True)
```

(with django 1.8 ?) when we write this queryset: `ModelB.objects.order_by('pk')`, it will in background order by `modela__name`.
We need to order the queryset by `modela_id` explicitely:

```python
from chunkator import chunkator
for item in chunkator(ModelB.objects.all(), 200, order_by='modela_id'):
    do_something(item)
```

**Edit**: it is possible to fix this case without changing the API. See PR #20

**Comment by brunobord** [comment]
closed by #20
