### ISSUE TITLE
FYI: works with Django 2.0.5

### ISSUE THREAD

**Issue by dkvdm** [novafloss/django-chunkator#29]
I've been using it with Django 2.0.5 without an issue. Just wanted to give a heads up that you can probably add this to the supported versions list.

**Comment by brunobord** [comment]
yep probably. we'll surely need to rearrange our test grid for that, but I'm glad that chunkator is 2.0.x ready :o)

**Comment by brunobord** [comment]
We can confirm that django-chunkator works up to the 2.1 version.
