### ISSUE TITLE
If queryset was ordered prior to calling `chunkator` would this ordering be preserved?

### ISSUE THREAD

**Issue by polinom** [novafloss/django-chunkator#38]
If queryset was ordered prior to calling `chunkator` would this ordering be preserved?

**Comment by k4nar** [comment]
No, chunkator order the queryset by pk: https://github.com/peopledoc/django-chunkator/blob/master/chunkator/__init__.py#L27-L33

However you could the same think than chunkator with another field, given that it's unique & not nullable.

**Comment by brunobord** [comment]
@polinom : do you think  we answered your question so we can close this issue?

**Comment by brunobord** [comment]
it looks like the issue is closed. If not, please do not hesitate to reopen this one.
